DROP TABLE IF EXISTS account CASCADE;

CREATE TABLE account (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS board CASCADE;

CREATE TABLE board (
	seq BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	writer VARCHAR(20) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	cnt INT DEFAULT 0
);

DROP TABLE IF EXISTS comment CASCADE;

CREATE TABLE comment (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	board_id BIGINT,
	nickname varchar(255),
	body TEXT,
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (board_id) REFERENCES board(seq) ON DELETE CASCADE 
);